mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^risk/', include('risk.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/risk/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^([a-z]{2,10})/$', views.index),
]

mysite/risk/models.py
from django.db import models

# Create your models here.

mysite/risk/forms.py
from django import forms

class PortfolioForm(forms.Form):
    ticker = forms.CharField(label='Ticker', widget=forms.TextInput(attrs={'class': 'form-control'}))
    weight = forms.CharField(label='Weight List', widget=forms.TextInput(attrs={'class': 'form-control'}))
    initial = forms.DecimalField(label='Initial Investment', widget=forms.TextInput(attrs={'class': 'form-control'}))
    rollingWindow = forms.IntegerField(label='Rolling Window Length (Year)', required=False, max_value=10, min_value=1, widget=forms.TextInput(attrs={'class': 'form-control'}))
    dataWindow = forms.IntegerField(label='Data Length (Year)', max_value=20, min_value=1, widget=forms.TextInput(attrs={'class': 'form-control'}))
    startDate = forms.DateField(label='Position Date', widget=forms.DateInput(attrs={'class': 'form-control', 'data-provide': 'datepicker'}))
    endDate = forms.DateField(label='End Date', widget=forms.DateInput(attrs={'class': 'form-control', 'data-provide': 'datepicker'}))
    varp = forms.DecimalField(label='VaR Probability', required=False, max_value=0.9999, min_value=0.0001, decimal_places=4, widget=forms.TextInput(attrs={'class': 'form-control'}))
    esp = forms.DecimalField(label='ES Probability', required=False, max_value=0.9999, min_value=0.0001, decimal_places=4, widget=forms.TextInput(attrs={'class': 'form-control'}))
    nday = forms.IntegerField(label='N Day Horizon (Day)', required=False, max_value=2520, min_value=1, widget=forms.TextInput(attrs={'class': 'form-control'}))
    method = forms.ChoiceField(label='Calculation Method', required=False, choices=[('PAR','Parametric'),('HIS','Historical'),('MC','Monte Carlo')], widget=forms.Select(attrs={'class': 'form-control'}))
    plotType = forms.ChoiceField(label='Plot Type', choices=[('PV','Portfolio Value'),('VAR','Value at Risk (VaR)'),('ES','Expected Shortfall (ES)')], widget=forms.RadioSelect(attrs={'class': 'form-control radio-sel'}))

class OptionForm(forms.Form):
    ticker = forms.CharField(label='Ticker', widget=forms.TextInput(attrs={'class': 'form-control'}))
    initial = forms.DecimalField(label='Initial Investment', widget=forms.TextInput(attrs={'class': 'form-control'}))
    window = forms.IntegerField(label='Rolling Window Length (Year)', max_value=10, min_value=1, widget=forms.TextInput(attrs={'class': 'form-control'}))
    startDate = forms.DateField(label='Position Date', widget=forms.DateInput(attrs={'class': 'form-control'}))
    endDate = forms.DateField(label='End Date', widget=forms.DateInput(attrs={'class': 'form-control'}))
    varp = forms.DecimalField(label='VaR Probability', max_value=0.9999, min_value=0.0001, decimal_places=4, widget=forms.TextInput(attrs={'class': 'form-control'}))
    esp = forms.DecimalField(label='ES Probability', max_value=0.9999, min_value=0.0001, decimal_places=4, widget=forms.TextInput(attrs={'class': 'form-control'}))
    nday = forms.IntegerField(label='N Day Horizon (Day)', max_value=2520, min_value=1, widget=forms.TextInput(attrs={'class': 'form-control'}))
    method = forms.ChoiceField(label='Calculation Method', choices=[('PAR','Parametric'),('HIS','Historical'),('MC','Monte Carlo')], widget=forms.Select(attrs={'class': 'form-control'}))
    plotType = forms.ChoiceField(label='Plot Type', choices=[('PV','Portfolio Value'),('VAR','Value at Risk (VaR)'),('ES','Expected Shortfall (ES)')], widget=forms.RadioSelect(attrs={'class': 'form-control radio-sel'}))

mysite/risk/views.py
from __future__ import division

from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import redirect

import json
from datetime import datetime
import dateutil.relativedelta
import numpy as np
from scipy.stats import norm

from .forms import PortfolioForm
from .forms import OptionForm

import pandas_datareader.data as web
import pandas as pd

import plotly.offline as py
import plotly.graph_objs as go

def index(request, version='default'):
    if (version == 'portfolio'):
        return render_portfolio(request)
    elif (version == 'option'):
        return render_option(request)
    else:
        return redirect('/risk/portfolio/')

def render_portfolio(request):
    if request.method == 'POST':
        form = PortfolioForm(request.POST)
        if form.is_valid():
            ticker = form.cleaned_data['ticker'].replace(' ','').split(",")
            weight = form.cleaned_data['weight'].replace(' ','').split(",")
            initial = form.cleaned_data['initial']
            rollingWindow = form.cleaned_data['rollingWindow']
            dataWindow = form.cleaned_data['dataWindow']
            startDate = form.cleaned_data['startDate']
            endDate = form.cleaned_data['endDate']
            varp = form.cleaned_data['varp']
            esp = form.cleaned_data['esp']
            nday = form.cleaned_data['nday']
            method = form.cleaned_data['method']
            plotType = form.cleaned_data['plotType']
            
            if (rollingWindow is None):
                rollingWindow = 5
            if (varp is None):
                varp = 0.99
            if (esp is None):
                esp = 0.975
            if (nday is None):
                nday = 5
            if (method is None):
                method = "PAR"
            
            initial = float(initial)
            varp = float(varp)
            esp = float(esp)
            
            if (plotType == "PV"):
                rollingdata = rollingdata_from_tickerlist(ticker, dataWindow, endDate)
                pricedata = positionprice_from_tickerlist(ticker, startDate)
                sharelist = calculate_share(initial, pricedata, ticker, weight)
                pv = calculate_portfolio_value(ticker, sharelist, rollingdata)
                jsonData = plot_portfolio(pv)
                return render(request, 'risk/index.html', {'plotValue': jsonData, 'version': 'portfolio', 'title': 'Portfolio Value'})
            elif (method == "PAR"):
                rollingdata = rollingdata_from_tickerlist(ticker, dataWindow+rollingWindow, endDate)
                pricedata = positionprice_from_tickerlist(ticker, startDate)
                sharelist = calculate_share(initial, pricedata, ticker, weight)
                pv = calculate_portfolio_value(ticker, sharelist, rollingdata)
                gbmData = calculate_nyear_mu_sig(pv, rollingWindow)
                if (plotType == "VAR"):
                    title = 'Parametric VaR'
                    data = calculate_pvar(gbmData, initial, varp, nday)
                elif (plotType == "ES"):
                    title = 'Parametric ES'
                    data = calculate_pes(gbmData, initial, esp, nday)
                else:
                    return redirect('/risk/portfolio/')
                jsonData = plot_portfolio(data)
                return render(request, 'risk/index.html', {'plotValue': jsonData, 'version': 'portfolio', 'title': title})
            elif (method == "HIS"):
                rollingdata = rollingdata_from_tickerlist(ticker, dataWindow+rollingWindow, endDate)
                pricedata = positionprice_from_tickerlist(ticker, startDate)
                sharelist = calculate_share(initial, pricedata, ticker, weight)
                pv = calculate_portfolio_value(ticker, sharelist, rollingdata)
                ndayGBMData = calculate_nday_horizon_mu(pv, nday)
                if (plotType == "VAR"):
                    title = 'Historical VaR'
                    data = calculate_hvar(ndayGBMData, initial, varp, nday)
                elif (plotType == "ES"):
                    title = 'Historical ES'
                    data = calculate_hes(ndayGBMData, initial, esp, nday)
                else:
                    return redirect('/risk/portfolio/')
                jsonData = plot_portfolio(data)
                return render(request, 'risk/index.html', {'plotValue': jsonData, 'version': 'portfolio', 'title': title})
            else:
                return redirect('/risk/portfolio/')
    else:
        form = PortfolioForm(initial={'ticker':'AAPL,MSFT', 'weight':'0.5,0.5','initial':'10000', 'rollingWindow':'5', 'dataWindow':'1', 'startDate':'2016-1-1', 'endDate':'2016-12-31', 'varp':'0.99', 'esp':'0.975', 'nday':'5'})
    return render(request, 'risk/index.html', {'portfolioForm': form, 'version': 'portfolio', 'title': 'Portfolio Value'})

def render_option(request):
    if request.method == 'POST':
        form = OptionForm(request.POST)
        if form.is_valid():
            ticker = form.cleaned_data['ticker'].replace(' ','').split(",")
            initial = form.cleaned_data['initial']
            window = form.cleaned_data['window']
            startDate = form.cleaned_data['startDate']
            endDate = form.cleaned_data['endDate']
            varp = form.cleaned_data['varp']
            esp = form.cleaned_data['esp']
            nday = form.cleaned_data['nday']
            method = form.cleaned_data['method']
            #data = dataframe_from_tickerlist(ticker, startDate, endDate)
            #jsonData = plot_historical_price(ticker, data)
            #return render(request, 'risk/index.html', {'plot': jsonData})
    else:
        form = OptionForm(initial={'ticker':'AAPL', 'initial':'10000', 'window':'10', 'startDate':'2000-1-1', 'endDate':'2010-12-31', 'varp':'0.99', 'esp':'0.975', 'nday':'5'})
    return render(request, 'risk/index.html', {'optionForm': form, 'version': 'option'})


def rollingdata_from_tickerlist(tickerlist, window, endDate):
    if (isinstance(endDate, str)):
        endDate = datetime.strptime(endDate, "%Y-%m-%d")
    startDate = endDate-dateutil.relativedelta.relativedelta(years = window)
    startDate = startDate.strftime("%Y-%m-%d")
    return dataframe_from_tickerlist(tickerlist, startDate, endDate)

def positionprice_from_tickerlist(tickerlist, positionDate):
    if (isinstance(positionDate, str)):
        positionDate = datetime.strptime(positionDate, "%Y-%m-%d")
    endDate = positionDate+dateutil.relativedelta.relativedelta(days = 10)
    endDate = endDate.strftime("%Y-%m-%d")
    data = dataframe_from_tickerlist(tickerlist, positionDate, endDate)
    return data.head(1)

#dataframe_from_tickerlist(["AAPL","TSLA"],"2016-1-31","2016-12-31")
def dataframe_from_tickerlist(tickerlist, startDate, endDate):
    data = {}
    for t in tickerlist:
        attempts = 0
        while attempts < 5:
            try:
                data[str.format(t)] = web.DataReader(t, 'yahoo', startDate, endDate)['Adj Close'].rename(t)
                break
            except:
                if (attempts >= 4):
                    raise
                attempts += 1
    data = pd.DataFrame(data)
    return data

def calculate_share(initial, pricedata, tickerlist, weightlist=[1]):
    if (len(tickerlist) != len(weightlist)):
        raise ValueError('Ticker and weight length mismatch.')
    share = {}
    i = 0
    for t in tickerlist:
        share[t] = float(weightlist[i])*float(initial)/float(pricedata[t][0])
        i = i+1
    return share

def calculate_portfolio_value(tickerlist, sharelist, rollingdata): 
    pv = pd.DataFrame()
    for t in tickerlist: 
        if (pv.empty):
            pv = rollingdata[t]*sharelist[t]
        else:
            pv = pv + rollingdata[t]*sharelist[t]
    pv = pd.DataFrame(pv)
    return pv
    
def plot_portfolio(data):
    dates = data.index.tolist()
    dates = [date.strftime("%Y-%m-%d") for date in dates]
    values = data.values.tolist()
    values = [value[0] for value in values]
    return json.dumps({'x':dates, 'y':values})

def calculate_nyear_mu_sig(data, nyear):
    port_log_return = np.log(data).diff().dropna()
    port_name = list(port_log_return)[0]
    port_len = port_log_return.shape[0]
    nday = int(np.ceil(nyear*252))
    port_log_return["mu"] = np.nan
    port_log_return["sig"] = np.nan
    i = nday-1
    while (i < port_len):
        avg = np.mean(port_log_return[port_name][(i-nday+1):(i+1)])
        std = np.sqrt(np.mean(port_log_return[port_name][(i-nday+1):(i+1)]**2)-avg**2)
        sig = std*np.sqrt(252)
        mu = avg*252+sig**2/2
        port_log_return["mu"][i] = mu
        port_log_return["sig"][i] = sig
        i = i+1
    return port_log_return.iloc[(nday-1):port_len]
    
def calculate_pvar(data, initial, varp, nday):
    varT = float(nday)/252
    var = pd.DataFrame()
    var['var'] = initial-initial*np.exp(data['sig']*np.sqrt(varT)*norm.ppf(1-varp)+(data['mu']-data['sig']**2/2)*varT)
    return var
    
def calculate_pes(data, initial, esp, nday):
    esT = float(nday)/252
    es = pd.DataFrame()
    es['es'] = initial-initial*np.exp(data['mu']*esT)*norm.cdf(norm.ppf(1-esp)-data['sig']*np.sqrt(esT))/(1-esp)
    return es
    
def calculate_nday_horizon_mu(data, nday):
    port_data = pd.DataFrame(index=data.index)
    port_name = list(data)[0]
    port_len = data.shape[0]
    i = nday
    port_data['nmu'] = np.nan
    while (i < port_len):
        port_data['nmu'][i] = np.log(data[port_name][i]/data[port_name][i-nday])
        i = i+1
    return port_data.iloc[(nday):port_len]

def calculate_hvar(data, initial, varp, nyear):
    port_data = pd.DataFrame(index=data.index)
    port_len = data.shape[0]
    nday = int(np.ceil(nyear*252))
    i = nday-1
    port_data['hvar'] = np.nan
    while (i < port_len):
        v = data['nmu'][(i-nday+1):(i+1)].nsmallest(int(np.ceil((nday)*(1-varp))))

mysite/risk/templates/risk/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <title>Risk Calculation System</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'risk/style.css' %}" />
  </head>
  <body>
    <div class="sidenav">
      <a href="/risk/portfolio/">Portfolio</a>
      <a href="/risk/option/">Option</a>
    </div>

    <div class="main">
      {% if version == "portfolio" %}
      <div class="risk-title">Portfolio</div>
      <div class="risk-subtitle">Portfolio VaR and ES Calculation...</div>
      <div class="risk-data">
        {% if portfolioForm %}
        <form action="/risk/portfolio/" method="post">
          {% csrf_token %}
          <table class='risk-table'>
            {{ portfolioForm }}
          </table>
          <button type="submit" class="btn btn-outline-primary btn-lg btn-block btn-cal">Calculate</button>
        </form>
        {% endif %}
      </div>
      {% endif %}
      {% if version == "option" %}
      <div class="risk-title">Option</div>
      <div class="risk-subtitle">Option VaR and ES Calculation...</div>
      <div class="risk-data">
        {% if optionForm %}
        <form action="/risk/option/" method="post">
          {% csrf_token %}
          <table class='risk-table'>
            {{ optionForm }}
          </table>
          <button type="submit" class="btn btn-outline-primary btn-lg btn-block btn-cal">Calculate</button>
        </form>
        {% endif %}
      </div>
      {% endif %}

      {% if plotValue %}
      <div id="plot-container">
        <div id="plot"></div>
        <a id="download-link" download="data.csv" href=# class="btn btn-outline-primary btn-lg btn-block btn-cal">Download Data</a>
      </div>
      {% endif %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <!-- Plotly.js -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script type="text/javascript">
      {% if portfolioForm or optionForm %}
      $.fn.datepicker.defaults.format = "yyyy-mm-dd";
      $.fn.datepicker.defaults.endDate = "-1d";
      $('#id_startDate').datepicker();
      $('#id_endDate').datepicker();
      $('.errorlist').addClass("alert alert-danger");

      $('#id_plotType_0').on('change', function() {
        //Portfolio Value
        $(".risk-table :input").prop("disabled", false);
        $('#id_rollingWindow').prop('disabled', true);
        $('#id_varp').prop('disabled', true);
        $('#id_esp').prop('disabled', true);
        $('#id_nday').prop('disabled', true);
        $('#id_method').prop('disabled', true);
      });
      $('#id_plotType_1').on('change', function() {
        //VaR
        $(".risk-table :input").prop("disabled", false);
        $('#id_esp').prop('disabled', true);
      });
      $('#id_plotType_2').on('change', function() {
        //ES
        $(".risk-table :input").prop("disabled", false);
        $('#id_varp').prop('disabled', true);
      });
      {% endif %}

      {% if plotValue %}
        function JSONtoCSV(obj) {
          var x = obj['x'];
          var y = obj['y'];
          var ret = "Date%2CValue%0A";
          for (i = 0; i < x.length; i++) {
            ret = ret+x[i]+"%2C";
            if (i < y.length)
              ret = ret+y[i]+"%0A";
            else
              ret = ret+"NA%0A";
          }
          return ret;
        }

        var plotData = jQuery.parseJSON('{{ plotValue|safe }}');
        var data = [
          {
            x: plotData['x'],
            y: plotData['y'],
            type: 'scatter',
            name: '{{ title }}',
          }
        ];
        var layout = {
          title: '{{ title }}'+" Chart",
          xaxis: {
            title: 'Date',
            rangeslider: {}
          },
          yaxis: {
            title: '{{ title }}'
          },
          showlegend: true
        }
        Plotly.newPlot('plot', data, layout);
        $('#download-link').attr('href',"data:application/octet-stream,"+JSONtoCSV(plotData));
      {% endif %}
    </script>
  </body>
</html>